config/routes.rb
StaticSite::Application.routes.draw do

  get '/about-us' => 'pages#about', as: :about
  get '/privacy' => 'pages#privacy'

  root 'pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # anything we want
  end

  def about
    # anything else
  end

  def privacy
    # stuff
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StaticSite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>Nav will go here
<%= link_to "Home", root_path %>
<%= link_to "About Us", about_path %>
<%= link_to "Privacy", privacy_path %>
  </nav>

  <%= yield %>

  <footer>(c) 2013</footer>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
  <p>
    Some math...
    <h4>
      <%= Time.now.strftime('Today is %A, it\'s %I:%M') %>
    </h4>
<!--    <ol>
      <li>Add an '/about-us' page. (Route '/about-us' to Pages controller and the about action.)</li>
      <li>Do some math with erb tags in the views</li>
      <li>Use git to add, commit and push your files</li>
    </ol>
    Submit a link to your repository.
  </p>
-->

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/privacy.html.erb
<h1>Privacy Policy</h1>
<p>We won't share your data, except with the NSA. Sorry, not our fault. :-(</p>


<%= "Hi there!".upcase %>
<br />
<br />
<% ["dog", "cat"].each do |animal| %>
<p><%= animal %></p>
<% end %>



<br />
<br />
Hi there!
<br />
<br />